/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package encryptiondecryption

import kotlin.test.Test
import kotlin.test.assertEquals

class EncryptionTest {
    @Test fun testShifting() {
        val out = encryptWithKeyShift("Pinoystat", 1)
        assertEquals("Qjopztubu", out)
    }

    @Test fun testShifting2() {
        val out = encryptWithKeyShift("AbCd", 25)
        assertEquals("ZaBc", out)
    }
    @Test fun testUnicodeAlgo(){
        val out = encryptWithKeyUnicode("Hello", 1)
        assertEquals("Ifmmp", out)
    }

    @Test fun testUnicodeAlgo2(){
        val out = encryptWithKeyUnicode("Hello", 25)
        assertEquals("a~\u0085\u0085\u0088", out)
    }
}
